#ifndef __MSGEVENT_H__
#define __MSGEVENT_H__

enum SERIAL_MSG_EVENT
{
	SERIAL_RECV_CHN1_EVENT = 5,
    SERIAL_RECV_CHN2_EVENT ,
    SERIAL_MONITOR_CHN1_EVENT ,
    SERIAL_MONITOR_CHN2_EVENT ,
};

#endif